environment:
  matrix:
    - TARGET: i686-pc-windows-gnu
      CHANNEL: nightly
    - TARGET: i686-pc-windows-msvc
      CHANNEL: nightly
    - TARGET: x86_64-pc-windows-gnu
      CHANNEL: nightly
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: nightly

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

build: false
shallow_clone: true

before_build:
  - rustup install nightly
  - cargo +nightly install clippy --force
  - cargo +nightly install rustfmt-nightly --force

test_script:
  - cargo test
  - cargo +nightly clippy
  - cargo +nightly fmt -- --write-mode diff

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

cache:
  - target
  - C:\Users\appveyor\.cargo\registry
