name: Clippy 

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install stable rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Prepare
      run: |
        sudo apt update
        wget -q https://hg.mozilla.org/mozilla-central/raw-file/default/python/mozboot/bin/bootstrap.py -O bootstrap.py
        python bootstrap.py --application-choice=browser --no-interactive|| exit 0
    - name: Build
      run: |
        export SHELL=/bin/bash
        cargo build --verbose
    - name: Clippy check
      uses: actions-rs/clippy-check@annotations-fallback
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests
      run: cargo test --verbose